name: Add file to GitHub
on: [push]

jobs:
  add-random-file:
    runs-on: ubuntu-latest
    steps:
      - name: Init Git Repository
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git pull origin main
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - name: Create Log File
        run: |
          git log --oneline >> log.txt
          ls -a
      - name: Save Log File
        run: |
          git add log.txt
          git commit -m "Added log file"
          git push origin master:main