name: Add file to GitHub
on: [push]

jobs:
  add-random-file:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"

      - name: Init Git Repository
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git pull origin main
          ls -a
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git log --oneline >> log.txt
          ls -a
          git add log.txt
          git commit -m "Added log file"
          git push origin master:main