name: "JS Actions"
on: [push]

jobs:
  run-js-actions:
    runs-on: ubuntu-latest
    steps:
      - name: JS Action Greeting Message
        id: Greet
        uses: actions/git-actions-demo@main
        with:
          who-to-greet: John